### ISSUE TITLE
Ratelimits not working

### ISSUE THREAD

**Issue by thorstenkramm** [xuqingfeng/caddy-rate-limit#11]
I tried to use the ratelimit in Caddy 0.9.5. caddy -plugins says "http.ratelimit" is included.

My conf is the following:
```
my.webserver.dev:80 {
    ratelimit /assets/uikit/vendor/jquery.js 1 1 minute
    root /var/www/my.webserver.dev/
    fastcgi / /run/php/php7.0-fpm.sock php {
        env CI_ENV development
    }
    log /var/log/caddy/access.log
    errors /var/log/caddy/error.log
    rewrite / {
      ext !.png !.css !.js !.otf !.ttf !.woff !.woff2 !.svg !.ico
      to /index.php
    }
}  
```
Using `ab -n 30 -c 5 http://my.webserver.dev/assets/uikit/vendor/jquery.js` or using curl with a simple bash while loop always returns HTTP 200. The ratelimit is not working.
Logfile says HTTP 200 to every request too. 
I tried with curly braces too, but it's not working either.
```
ratelimit 1 1 minute {
  /
  /assets
}
```
What am I doing wrong? 
Many thanks for every hint.

**Comment by xuqingfeng** [comment]
Possibly you have the same issue like https://github.com/xuqingfeng/caddy-rate-limit/issues/9

Notice: [Pirvate IP](https://github.com/xuqingfeng/caddy-rate-limit/blob/master/README.md#syntax) will be ignored.

**Comment by xuqingfeng** [comment]
Guess now it's working？

If you still have this problem feel free to reopen.
