### ISSUE TITLE
Ratelimit all paths except

### ISSUE THREAD

**Issue by dmyersturnbull** [xuqingfeng/caddy-rate-limit#14]
I have a lot of paths directly under `/`. Just about every resource should be ratelimited, except for static resources like Javascripts and CSS, which don't strain the server much and also need to be accessed frequently. It would be great to be able to apply a ratelimit to all paths except for some, like:

```
ratelimit 30 1 minute {
    [^resources]
}
```

**Comment by xuqingfeng** [comment]
Good point!

I will look into it.

**Comment by xuqingfeng** [comment]
@dmyersturnbull I have pushed some code to implement this feature.

Can you help test if it's working? (By build caddy from source with [this](https://github.com/xuqingfeng/caddy-rate-limit/tree/feature-ignore-path)  branch of `caddy-rate-limit`)

**Comment by xuqingfeng** [comment]
Merged
