### ISSUE TITLE
rate limit based on jwt

### ISSUE THREAD

**Issue by OmgImAlexis** [xuqingfeng/caddy-rate-limit#15]
After reading through the README I'm guessing this is based on per IP address it'd be great to be able to base this on per jwt, this wouldn't even need to decode the token just simply use the Authorization header's value instead of an ip.

**Comment by xuqingfeng** [comment]
Indeed, this plugin is based on client IP address.

Not sure if there is a wide use case for `auth token`.

**Comment by OmgImAlexis** [comment]
The reason for wanting this is to rate limit an API based on users instead of per IP that way each API key can be used on multiple devices but have a global limit.

**Comment by xuqingfeng** [comment]
Sorry for the late reply...

I get your point and `limit by the request header` is probably what you want, I will look into it.

**Comment by jnylen** [comment]
Hi, this would be wonderful. And if possible to mix ip and request header in the check would be nice.

**Comment by xuqingfeng** [comment]
> mix ip and request header in the check

@jnylen You mean if the request header is empty/missing it should fall back to the default(ip) policy?

Or you only want to apply the ratelimit only if the request header is matching xxx?

**Comment by xuqingfeng** [comment]
This feature has been implemented and released to [caddyserver](https://caddyserver.com/docs/http.ratelimit).
