### ISSUE TITLE
Whitelist by CIDR

### ISSUE THREAD

**Issue by sporkmonger** [xuqingfeng/caddy-rate-limit#17]
e.g. You may want to whitelist your own office NAT's IP address/CIDR from the rate limit as presumably your office will hit your own domain far more often than any other legitimate IP.

I actually started to write a PR for this, but it seemed likely that it would likely require a pretty decent refactor to implement.

**Comment by xuqingfeng** [comment]
@sporkmonger I second your thoughts, it will be a bit tricky to implement this feature without breaking the backward compatibility.

the Caddyfile format might be:
```
ratelimit 1 2 second {
    whitelistIPs 1.2.3.4/32
    resource /static
}
```

**Comment by sporkmonger** [comment]
Yeah, that was about my thoughts on syntax as well. I think I'd prefer the shorter `whitelist` keyword to `whitelistIPs` since it's obvious from context, but otherwise yes.

**Comment by xuqingfeng** [comment]
Hi @sporkmonger I committed some code to master, could help to test it out?

I also changed the syntax a little bit(to keep it compatible with the old version):
```
ratelimit 1 2 second {
    whitelist 1.2.3.4/32
    /static
}
```
Note: I haven't released to caddy website yet.

**Comment by xuqingfeng** [comment]
Released to caddy website

**Comment by sporkmonger** [comment]
Awesome, thanks. I do think that maybe the syntax you mentioned earlier w/ `resource` keyword would be better long term. And just allow both syntaxes simultaneously to avoid breaking backwards compatibility.
