### ISSUE TITLE
Request - client bandwidth rate limit

### ISSUE THREAD

**Issue by magikstm** [xuqingfeng/caddy-rate-limit#19]
Would it be possible to add client bandwidth rate limit?

Possibly:
1) Speed limit based on path (ex: 200KB/s per file or for the entire path)
2) Bandwidth limit based on path (ex: 4GB/day)

I would like to use these for a specific project in order to limit user downloads.

I use that in Apache for the first one: https://httpd.apache.org/docs/trunk/mod/mod_ratelimit.html

**Comment by xuqingfeng** [comment]
@magikstm that's an interesting use case and it might worth another plugin instead of put it in rate-limit.

**Comment by xuqingfeng** [comment]
Closing as won't implement.
