### ISSUE TITLE
Rate limit specific request methods

### ISSUE THREAD

**Issue by Siilwyn** [xuqingfeng/caddy-rate-limit#20]
:hand: is it possible to limit requests based on their method? For example limiting POST requests.

**Comment by xuqingfeng** [comment]
It's definitely possible.

maybe something like:
```
ratelimit rate burst unit {
    methods url
}

ratelimit 2 2 minute {
    * /all
    get,post /api
}
```

**Comment by Siilwyn** [comment]
Yes, that looks very good. Can't help with the coding as I sadly don't know Go.

**Comment by xuqingfeng** [comment]
The functionality is finished, but syntax is a bit different from what I posted above, I will release to caddy webiste in comming days.

```
ratelimit methods rate burst unit {
    whitelist CIDR
    resources
}
```

**Comment by Siilwyn** [comment]
Hooray, thank you for this feature and creating this Caddy plugin!

**Comment by xuqingfeng** [comment]
Released. 

Let me know if you have problems when using this feature.

Closing as done.
