### ISSUE TITLE
[Feature] allow import directive within ratelimit

### ISSUE THREAD

**Issue by root360-AndreasUlm** [xuqingfeng/caddy-rate-limit#21]
Hi,

we several services with changing IP addresses connecting to our Caddy instance.
These should be whitelisted for the ratelimits.
To allow dynamically adding IPs to the whitelist it would be nice to write those IPs into a file and import that one within a ratelimit block using the Caddy import directive.

Currently the validation fails with the following error:
`$ caddy -conf /etc/caddy/Caddyfile -validate                                                                                                        
2017/12/18 12:15:22 /etc/caddy/load.d/ratelimit:7 - Error during parsing: expecting whitelist, got import `

Would this be possible to implement?

Cheers,
Andreas

**Comment by xuqingfeng** [comment]
Actually, you can specify an IP range([CIDR](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing)) you want to whitelist.

And `import` cannot be used inside of other directives(docs [here](https://caddyserver.com/docs/import)),  but you can import the whole rate-limit config, after you updated `whitelist` in rate-limit config, just reload caddy.

**Comment by root360-AndreasUlm** [comment]
Thanks for the reply.
I'm already writing the whole ratelimit directive in a file which is then imported.
For now it's working fine.
