### ISSUE TITLE
Sudden death of Caddy due to ratelimit

### ISSUE THREAD

**Issue by root360-AndreasUlm** [xuqingfeng/caddy-rate-limit#23]
Hi,

we face several sudden death of Caddy during a day and found that deactivating ratelimit solves this.

Our setup:
* Caddy 0.10.10
* AWS EC2 instance (Ubuntu 14.04) with AWS EIP directly connecting to the internet
* Caddy redirects 1700+ domains to other domains
* ratelimit configuration:
```
ratelimit / 300 400 minute {
  # 175 whitelisted IP addresses like this:
  whitelist x.x.x.x/32
  (...)
}
```

Request statistics:
* 120000- 300000 requests per day
* 4000 - 15000 requests per hour
* 15000 - 17000 unique IP addresses per day
* 900 - 1600 unique IP addresses per hour

Increasing available memory of the system does not help and Caddy is not killed by the OOM-killer thus Caddy stops itself for an unknown reason.
My assumption is that the internal structure of the ratelimit plugin does not handle the volume of unique IP addresses well which forces Caddy to stop without any log message.

Are these information enough to analyze the issue?

Best regards,
Andreas

**Comment by xuqingfeng** [comment]
@root360-AndreasUlm thanks for the thorough report. Sadly it's not easy for me to reproduce this issue. I will see what I can do.

In the meantime, I have improved the plugin gradually. Does this issue still occur in the latest version?

**Comment by xuqingfeng** [comment]
Closing for now.

Feel free to re-open it if this issue still occurs.
