### ISSUE TITLE
RetryAfter is called even if the request is not getting a 429

### ISSUE THREAD

**Issue by julsemaan** [xuqingfeng/caddy-rate-limit#24]
First, thanks for this nice piece of code, I'm adapting it now for one of my use cases but I'm hitting an issue.

It seems that requests are being consumed twice as fast because of this line here:
https://github.com/xuqingfeng/caddy-rate-limit/blob/master/ratelimit.go#L81

From what the docs of "golang.org/x/time/rate" say, calling Reserve() will consume a token, so RetryAfter() should only be called if the request isn't allowed from what I can tell.

Let me know if you want a PR or you'll fix that on your side.

Cheers!

**Comment by xuqingfeng** [comment]
@julsemaan good point, pls send a PR.
