### ISSUE TITLE
Thanks for making this plugin

### ISSUE THREAD

**Issue by mholt** [xuqingfeng/caddy-rate-limit#27]
Not an issue - just wanted to write and say thank you for making and maintaining this plugin. It has received probably more praise than you know, and makes quite a few people happy to use Caddy. This plugin is one of the top 10 downloaded. Keep up the great work 👍 and thanks again!

**Comment by xuqingfeng** [comment]
Thanks mholt. 

Caddy is a very useful tool and it's my pleasure to have a chance to contribute to caddy.
