### ISSUE TITLE
tag v1.6.0 concurrent map read and map wirte panic  <ratelimit.go:90>

### ISSUE THREAD

**Issue by cdongyang** [xuqingfeng/caddy-rate-limit#38]
https://github.com/xuqingfeng/caddy-rate-limit/blob/502904915cc20e1909f09a2c06acc055b9b292a2/ratelimit.go#L90

{"log":"fatal error: concurrent map read and map write\n","stream":"stderr","time":"2019-06-10T04:09:30.643733096Z"}
{"log":"\n","stream":"stderr","time":"2019-06-10T04:09:30.647184373Z"}
{"log":"goroutine 300764 [running]:\n","stream":"stderr","time":"2019-06-10T04:09:30.647197951Z"}
{"log":"runtime.throw(0xf7f318, 0x21)\n","stream":"stderr","time":"2019-06-10T04:09:30.649689091Z"}
{"log":"\u0009/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc000416d98 sp=0xc000416d68 pc=0x42d7c2\n","stream":"stderr","time":"2019-06-10T04:09:30.650086122Z"}
{"log":"runtime.mapaccess2_faststr(0xe10c40, 0xc000101590, 0xc000638ea0, 0xe, 0x1, 0xc000638ea0)\n","stream":"stderr","time":"2019-06-10T04:09:30.650091018Z"}
{"log":"\u0009/usr/local/go/src/runtime/map_faststr.go:116 +0x4a9 fp=0xc000416e08 sp=0xc000416d98 pc=0x412cd9\n","stream":"stderr","time":"2019-06-10T04:09:30.650094601Z"}
{"log":"ih5.cn/vendor/github.com/xuqingfeng/caddy-rate-limit.RateLimit.ServeHTTP(0x10c1480, 0xc000211080, 0xc000228600, 0x1, 0x1, 0x10d2660, 0xc0006c1620, 0xc002307b00, 0x100000000000008, 0x0, ...)\n","stream":"stderr","time":"2019-06-10T04:09:30.650101534Z"}
{"log":"\u0009/Users/vxplo/go/src/ih5.cn/vendor/github.com/xuqingfeng/caddy-rate-limit/ratelimit.go:90 +0x107b fp=0xc0004173d8 sp=0xc000416e08 pc=0xae6e9b\n","stream":"stderr","time":"2019-06-10T04:09:30.650105385Z"}
{"log":"ih5.cn/vendor/github.com/xuqingfeng/caddy-rate-limit.(*RateLimit).ServeHTTP(0xc0002110b0, 0x10d2660, 0xc0006c1620, 0xc002307b00, 0x0, 0x0, 0xc000210c00)\n","stream":"stderr","time":"2019-06-10T04:09:30.650108818Z"}

**Comment by htfy96** [comment]
Same. Is there any plan to fix this?

**Comment by xuqingfeng** [comment]
I will look into it.
