### ISSUE TITLE
Caddy v2 migration?

### ISSUE THREAD

**Issue by milanof-huma** [xuqingfeng/caddy-rate-limit#44]
Hi, any plan to get plugin for caddy v2?

**Comment by xuqingfeng** [comment]
Will look into it in the future, but no plan for the moment.

**Comment by hairyhenderson** [comment]
Caddy v2 is out now: https://github.com/caddyserver/caddy/releases/tag/v2.0.0

See https://caddyserver.com/docs/extending-caddy for information on the new module API

**Comment by Daniel-ltw** [comment]
Has anyone implemented something?

**Comment by xdu31** [comment]
> Caddy v2 is out now: https://github.com/caddyserver/caddy/releases/tag/v2.0.0
> 
> See https://caddyserver.com/docs/extending-caddy for information on the new module API

Hi @hairyhenderson & @xuqingfeng :

Recently I have been working with Caddy server and this ratelimiting plugin. I can work on updating this to Caddy v2 version

**Comment by hairyhenderson** [comment]
It's probably worth mentioning that @mholt has a new rate-limiting Caddy module in development: https://github.com/mholt/caddy-ratelimit

**Comment by xdu31** [comment]
> It's probably worth mentioning that @mholt has a new rate-limiting Caddy module in development: https://github.com/mholt/caddy-ratelimit

That's awesome, would like to try Matt's new implementation. @mholt

**Comment by xuqingfeng** [comment]
Closing, as this ticket is not needed anymore.
