### ISSUE TITLE
Not working with Caddy 0.9.5

### ISSUE THREAD

**Issue by Nixtren** [xuqingfeng/caddy-rate-limit#9]
Discussion here:
https://forum.caddyserver.com/t/ratelimit-not-taking-effect-when-proxy-is-used/1563

**Comment by xuqingfeng** [comment]
Are you testing on your local machine?

Notice: `Local IP` will be ignored: https://github.com/xuqingfeng/caddy-rate-limit/blob/master/ratelimit.go#L54

**Comment by gdhgdhgdh** [comment]
Nope - I had the same behaviour when I accessed the service via an AWS ELB, so there would be at least two separate client IPs accessing Caddy.

I was able to issue over a dozen cert requests without any slowdown or HTTP 429 messages.

Caddy is running in a container, but in `--net=host` mode, so it can see the IP address of the EC2 host machine.

**Comment by xuqingfeng** [comment]
@gdhgdhgdh Can you show me the IPs in caddy `access.log`.

**Comment by gdhgdhgdh** [comment]
Sure,

```
[root@palectro-dev-certservice-i08bae82503266ef24 certservice]# docker logs 91d
Activating privacy features... done.
http://0.0.0.0:2015
10.242.0.192 - [07/Mar/2017:10:39:51 +0000] "GET / HTTP/1.1" 200 639
10.242.1.254 - [07/Mar/2017:10:39:51 +0000] "GET / HTTP/1.1" 200 639
10.242.1.254 - [07/Mar/2017:10:39:56 +0000] "POST /api/v1/cfssl/newcert HTTP/1.1" 200 2222
10.242.0.192 - [07/Mar/2017:10:40:01 +0000] "POST /api/v1/cfssl/newcert HTTP/1.1" 200 2226
10.242.1.254 - [07/Mar/2017:10:40:01 +0000] "POST /api/v1/cfssl/newcert HTTP/1.1" 200 2226
10.242.0.192 - [07/Mar/2017:10:40:01 +0000] "POST /api/v1/cfssl/newcert HTTP/1.1" 200 2222
10.242.1.254 - [07/Mar/2017:10:40:01 +0000] "POST /api/v1/cfssl/newcert HTTP/1.1" 200 2222
10.242.0.192 - [07/Mar/2017:10:40:02 +0000] "POST /api/v1/cfssl/newcert HTTP/1.1" 200 2222
10.242.1.254 - [07/Mar/2017:10:40:02 +0000] "POST /api/v1/cfssl/newcert HTTP/1.1" 200 2226
10.242.0.192 - [07/Mar/2017:10:40:02 +0000] "POST /api/v1/cfssl/newcert HTTP/1.1" 200 2222
10.242.1.254 - [07/Mar/2017:10:40:03 +0000] "POST /api/v1/cfssl/newcert HTTP/1.1" 200 2222
10.242.0.192 - [07/Mar/2017:10:40:03 +0000] "POST /api/v1/cfssl/newcert HTTP/1.1" 200 2222
```

The whole Caddyfile is 

```
0.0.0.0:2015
prometheus 0.0.0.0:9180
ratelimit / 2 2 minute
proxy / localhost:8888
tls off
log stdout
```

**Comment by gdhgdhgdh** [comment]
And importantly, the IP address of the machine running Caddy..

```
[root@palectro-dev-certservice-i08bae82503266ef24 certservice]# ip r
default via 10.242.0.1 dev eth0 
10.242.0.0/24 dev eth0  proto kernel  scope link  src 10.242.0.195 
```

**Comment by xuqingfeng** [comment]
@gdhgdhgdh cool thanks.

`10.242.0.192` `10.242.1.254` are both `private IPs` and will be ignored - see https://en.wikipedia.org/wiki/Private_network

They are treated as `internal traffic`.

**Comment by gdhgdhgdh** [comment]
Yep, this is deployed in an AWS VPC (Virtual Private Cloud) with ELB (Elastic Load Balancer)- this is the default method for an AWS network to get traffic from Internet - hence your software can never work in AWS - I'm sure that's not desirable.

The traffic arrives on public IPs and then the AWS Elastic Load Balancer re-emits the traffic from a 10.x.x.x address inside the VPC.

Can this 'don't limit internal addresses' be switched off with config, since currently the plugin is useless for many use cases... ?

**Comment by gdhgdhgdh** [comment]
Adding the `realip` plugin works around the problem for me - I do think this `internal traffic` behaviour is confusing, tho'..

```
realip {
    from 10.0.0.0/8
}
```

**Comment by Nixtren** [comment]
Indeed I was testing on a local IP. Looks like everything is solved :)
